name: places
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  dio: ^5.2.0
  dart_code_metrics: ^4.17.1
  flutter_svg: ^1.1.4
  provider: ^6.0.4
  surf_lint_rules: ^1.5.0
  cached_network_image: ^3.2.3
  mobx: ^2.0.4
  flutter_mobx: ^2.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  redux: ^5.0.0
  flutter_redux: ^0.8.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  mobx_codegen: ^2.0.3

flutter:
  uses-material-design: true

  assets:
    - res/icons/hotels.svg
    - res/icons/restaurants.svg
    - res/icons/special_places.svg
    - res/icons/parks.svg
    - res/icons/museums.svg
    - res/icons/cafes.svg
    - res/icons/want_to_visited_empty.svg
    - res/icons/visited_empty.svg
    - res/icons/list_of_sights.svg
    - res/icons/map.svg
    - res/icons/heart.svg
    - res/icons/settings.svg
    - res/icons/page1.png
    - res/icons/page2.png
    - res/icons/page3.png
    - res/icons/search.png
    - res/icons/filter.png
    - res/icons/splash.png
    - res/icons/file.png
    - res/icons/photo.png
    - res/icons/camera.png
    - res/icons/calendar.png
    - res/icons/error.png
    - res/images/placeholder.png



  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto-Regular.ttf
