name: places
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dart_code_metrics: ^4.17.1
  flutter_svg: ^1.1.4
  provider: ^6.0.4
  surf_lint_rules: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - res/icons/hotels.png
    - res/icons/restaurants.png
    - res/icons/special_places.png
    - res/icons/parks.png
    - res/icons/museums.png
    - res/icons/cafes.png
    - res/icons/want_to_visited_empty.png
    - res/icons/visited_empty.png
    - res/icons/list_of_sights.png
    - res/icons/map.png
    - res/icons/heart.png
    - res/icons/settings.png

  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto-Regular.ttf
