name: places
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dart_code_metrics: ^4.17.1
  flutter_svg: ^1.1.4
  surf_lint_rules: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:
  uses-material-design: true
  
  assets:
    - res/
  
  fonts:
    - family: Roboto     
      fonts:
        - asset: res/fonts/Roboto-Regular.ttf

